export default [
  { name: "black", hex: "#000000" },
  { name: "white", hex: "#ffffff" },
  { name: "dark grey", hex: "#3C3F42" },
  { name: "light grey", hex: "#DADADA" },
  { name: "navy", hex: "#202A44" },
  { name: "light blue", hex: "#b3cee5" },
  { name: "dark blue", hex: "#00008B" },
  { name: "beige", hex: "#f5f5dc" },
  { name: "dark brown", hex: "#4E3524" },
  { name: "light brown", hex: "#c19a6b" },
  { name: "olive", hex: "#556b2f" },
  { name: "pink", hex: "#ffc0cb" },
  { name: "bordeaux", hex: "#5F021F" },
]
